In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [15]:
from sklearn.datasets import load_iris
data = load_iris()

In [16]:
type(data)

sklearn.utils._bunch.Bunch

In [17]:
type(data.data)

numpy.ndarray

In [18]:
dir(data)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [19]:
columns = data.feature_names
type(columns)

list

In [23]:
type(data.target_names)

numpy.ndarray

In [25]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [27]:
df = pd.DataFrame(data.data, columns = columns)
df['target'] = data.target

In [28]:
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [29]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,:-1],df.iloc[:,-1],test_size=0.30,random_state=32)

In [30]:
x_train

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
117                7.7               3.8                6.7               2.2
73                 6.1               2.8                4.7               1.2
97                 6.2               2.9                4.3               1.3
63                 6.1               2.9                4.7               1.4
49                 5.0               3.3                1.4               0.2
..                 ...               ...                ...               ...
88                 5.6               3.0                4.1               1.3
124                6.7               3.3                5.7               2.1
54                 6.5               2.8                4.6               1.5
133                6.3               2.8                5.1               1.5
43                 5.0               3.5                1.6               0.6

[105 rows x 4 columns]

In [31]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [32]:
gnb.fit(x_train,y_train)

GaussianNB()

In [34]:
y_pred = gnb.predict(x_test)

In [35]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45

[[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]
0.9777777777777777

In [36]:
import seaborn as sns

In [37]:
df = sns.load_dataset('tips')

In [38]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [40]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [41]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [42]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [43]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [44]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [51]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [56]:
df = df.reindex(columns=['sex','smoker','day','time','tip','total_bill','size'])

In [57]:
df.head()

      sex smoker  day    time   tip  total_bill  size
0  Female     No  Sun  Dinner  1.01       16.99     2
1    Male     No  Sun  Dinner  1.66       10.34     3
2    Male     No  Sun  Dinner  3.50       21.01     3
3    Male     No  Sun  Dinner  3.31       23.68     2
4  Female     No  Sun  Dinner  3.61       24.59     4

In [58]:
df.columns

Index(['sex', 'smoker', 'day', 'time', 'tip', 'total_bill', 'size'], dtype='object')

In [63]:
x = df.iloc[:,[0,1,2,4,5,6]]
y = df.iloc[:,3]

In [66]:
x

        sex smoker   day   tip  total_bill  size
0    Female     No   Sun  1.01       16.99     2
1      Male     No   Sun  1.66       10.34     3
2      Male     No   Sun  3.50       21.01     3
3      Male     No   Sun  3.31       23.68     2
4    Female     No   Sun  3.61       24.59     4
..      ...    ...   ...   ...         ...   ...
239    Male     No   Sat  5.92       29.03     3
240  Female    Yes   Sat  2.00       27.18     2
241    Male    Yes   Sat  2.00       22.67     2
242    Male     No   Sat  1.75       17.82     2
243  Female     No  Thur  3.00       18.78     2

[244 rows x 6 columns]

In [67]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.30,random_state=42)

In [71]:
x_train.shape,x_test.shape,y_train

((170, 6),
 (74, 6),
 234    Dinner
 227    Dinner
 180    Dinner
 5      Dinner
 56     Dinner
         ...
 106    Dinner
 14     Dinner
 92     Dinner
 179    Dinner
 102    Dinner
 Name: time, Length: 170, dtype: category
 Categories (2, object): ['Lunch', 'Dinner'])

In [76]:
x_train

        sex smoker  day   tip  total_bill  size
234    Male    Yes  Sat  3.00       15.53     2
227    Male     No  Sat  3.00       20.45     4
180    Male    Yes  Sun  3.68       34.65     4
5      Male     No  Sun  4.71       25.29     4
56     Male    Yes  Sat  3.00       38.01     4
..      ...    ...  ...   ...         ...   ...
106    Male    Yes  Sat  4.06       20.49     2
14   Female     No  Sun  3.02       14.83     2
92   Female    Yes  Fri  1.00        5.75     2
179    Male    Yes  Sun  3.55       34.63     2
102  Female    Yes  Sat  2.50       44.30     3

[170 rows x 6 columns]

In [96]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('onehot',OneHotEncoder(drop='first'),[0,1,2])],remainder='passthrough')

In [97]:
import sys
import numpy as np
np.set_printoptions(threshold=sys.maxsize)

x_train = ct.fit_transform(x_train)

In [99]:
x_test = ct.transform(x_test)

In [102]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [103]:
gnb.fit(x_train,y_train)

GaussianNB()

In [104]:
y_pred = gnb.predict(x_test)

In [105]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(classification_report(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))

              precision    recall  f1-score   support

      Dinner       0.95      1.00      0.97        52
       Lunch       1.00      0.86      0.93        22

    accuracy                           0.96        74
   macro avg       0.97      0.93      0.95        74
weighted avg       0.96      0.96      0.96        74

[[52  0]
 [ 3 19]]